piVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
        env:
          - name: HTTP_PROXY
            value: null
          - name: HTTPS_PROXY
            value: null
      - name: nodeserver
        image: bayedieyeba/nodeapp
        ports:
        - containerPort: 5000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31110
